# Series

O objeto fundamental do Pandas são as **Series**, uma classe do pandas.

As Series são as **colunas das tabelas** (que veremos mais a frente), e por baixo dos panos, os dados ficam armazenados como **numpy arrays**!

A diferença é que a série possui um **índice associado**, permitindo o acesso aos conteúdos dessa estrutura por ele, como um dicionário.

Além disso, as séries têm métodos específicos além dos que vimos pra arrays, o que será super útil!

Podemos criar uma série **a partir de uma lista**, usando a função do pandas `pd.Series()`:

In [1]:
import pandas as pd

In [2]:
lista = [4, 8, 9, 12]

serie = pd.Series(lista)
serie

0     4
1     8
2     9
3    12
dtype: int64

In [3]:
type(serie)

pandas.core.series.Series

In [4]:
serie.values

array([ 4,  8,  9, 12])

In [5]:
type(serie.values)

numpy.ndarray

Indice acesso

In [6]:
serie[1]

8

Valores

In [7]:
serie.values

array([ 4,  8,  9, 12])

Indice

In [8]:
serie.index

RangeIndex(start=0, stop=4, step=1)

Indice não numérico

In [9]:
lista = [4, 8, 9, 12]
indices = ['a', 'b', 'c', 'd']

In [10]:
serie = pd.Series(data=lista, index=indices)
serie

a     4
b     8
c     9
d    12
dtype: int64

In [11]:
serie[1]

/tmp/ipykernel_178916/844541441.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  serie[1]

8

In [12]:
serie.iloc[1]

8

In [13]:
serie['b']

8

Slicing

In [14]:
serie['b':'d']

b     8
c     9
d    12
dtype: int64

In [15]:
serie.loc[['a', 'd']]

a     4
d    12
dtype: int64

Filtros

In [16]:
lista = [4, 8, 9, 12]
indices = ['a', 'b', 'c', 'd']
serie = pd.Series(data=lista, index=indices)
serie

a     4
b     8
c     9
d    12
dtype: int64

In [17]:
mascara = serie >= 9 
mascara

a    False
b    False
c     True
d     True
dtype: bool

In [18]:
serie[mascara]

c     9
d    12
dtype: int64

Apply

In [19]:
lista = [4, 8, 9, 12]
indices = ['a', 'b', 'c', 'd']
serie = pd.Series(data=lista, index=indices)
serie

a     4
b     8
c     9
d    12
dtype: int64

In [20]:
def multiplicar_2(numero):
    return numero * 2

multiplicar_2(12)

24

In [21]:
lmultiplicar_2 = lambda numero: numero * 2

lmultiplicar_2(13)

26

In [22]:
serie.apply(multiplicar_2)

a     8
b    16
c    18
d    24
dtype: int64

In [23]:
serie.apply(lmultiplicar_2)

a     8
b    16
c    18
d    24
dtype: int64

Voltando novamente ao DataFrame

In [24]:
df = pd.read_csv('produtos.csv')
df.head()

,id,brand,name,price,price_sign,currency,image_link,product_link,website_link,description,rating,category,product_type,tag_list,created_at,updated_at,product_api_url,api_featured_image,product_colors
0,1048,colourpop,Lippie Pencil,5.0,$,CAD,https://cdn.shopify.com/s/files/1/1338/0845/co...,https://colourpop.com/collections/lippie-pencil,https://colourpop.com,Lippie Pencil A long-wearing and high-intensit...,NaN,pencil,lip_liner,"['cruelty free', 'Vegan']",2018-07-08T23:45:08.056Z,2018-07-09T00:53:23.301Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#B28378', 'colour_name': 'BFF ..."
1,1047,colourpop,Blotted Lip,5.5,$,CAD,https://cdn.shopify.com/s/files/1/1338/0845/pr...,https://colourpop.com/collections/lippie-stix?...,https://colourpop.com,Blotted Lip Sheer matte lipstick that creates ...,NaN,lipstick,lipstick,"['cruelty free', 'Vegan']",2018-07-08T22:01:20.178Z,2018-07-09T00:53:23.287Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#b72227', 'colour_name': ""Bee'..."
2,1046,colourpop,Lippie Stix,5.5,$,CAD,https://cdn.shopify.com/s/files/1/1338/0845/co...,https://colourpop.com/collections/lippie-stix,https://colourpop.com,"Lippie Stix Formula contains Vitamin E, Mango,...",NaN,lipstick,lipstick,"['cruelty free', 'Vegan']",2018-07-08T21:47:49.858Z,2018-07-09T00:53:23.274Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#F2DEC3', 'colour_name': 'Fair..."
3,1045,colourpop,No Filter Foundation,12.0,$,CAD,https://cdn.shopify.com/s/files/1/1338/0845/pr...,https://colourpop.com/products/no-filter-matte...,https://colourpop.com/products/no-filter-matte...,"Developed for the Selfie Age, our buildable fu...",NaN,liquid,foundation,"['cruelty free', 'Vegan']",2018-07-08T18:22:25.273Z,2018-07-09T00:53:23.313Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#F2DEC3', 'colour_name': 'Fair..."
4,1044,boosh,Lipstick,26.0,$,CAD,https://cdn.shopify.com/s/files/1/1016/3243/pr...,https://www.boosh.ca/collections/all,https://www.boosh.ca/,All of our products are free from lead and hea...,NaN,lipstick,lipstick,"['Chemical Free', 'Organic']",2018-07-08T17:32:28.088Z,2018-09-02T22:52:06.669Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#CB4975', 'colour_name': 'Babs..."

In [25]:
df.dtypes

id                      int64
brand                  object
name                   object
price                 float64
price_sign             object
currency               object
image_link             object
product_link           object
website_link           object
description            object
rating                float64
category               object
product_type           object
tag_list               object
created_at             object
updated_at             object
product_api_url        object
api_featured_image     object
product_colors         object
dtype: object

In [26]:
type(df['price'])

pandas.core.series.Series

In [27]:
df['price'].max()

77.0

In [28]:
df['price'].argmax()

364

In [29]:
df['price'].mean() # Erro misturei USD, com outra moedas...

16.508593238822247

In [30]:
df['price'].sort_values(ascending=False)

364    77.00
386    75.00
329    65.00
689    60.00
676    56.49
       ...
377      NaN
378      NaN
379      NaN
380      NaN
381      NaN
Name: price, Length: 931, dtype: float64

In [31]:
df.sort_values(by=['price'], ascending=False)

,id,brand,name,price,price_sign,currency,image_link,product_link,website_link,description,rating,category,product_type,tag_list,created_at,updated_at,product_api_url,api_featured_image,product_colors
364,662,dior,Dior Holiday Couture Collection,77.00,£,GBP,https://www.dior.com/beauty/version-5.14327481...,https://www.dior.com/beauty/en_gb/fragrance-be...,https://www.dior.com,A couture makeup bag with a selection of three...,NaN,lipstick,lipstick,[],2017-12-03T23:21:53.130Z,2017-12-23T20:58:42.309Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,[]
386,639,benefit,cheekathon bronzer & blush palette,75.00,NaN,NaN,https://www.benefitcosmetics.com/ca/sites/ca/f...,https://www.benefitcosmetics.com/ca/en-gb/prod...,https://www.benefitcosmetics.com,“kick up your cheeks” blush kit,NaN,NaN,bronzer,[],2016-10-02T11:37:26.478Z,2017-12-23T20:42:43.806Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,[]
329,697,dior,Couture Colour Wardrobe palette,65.00,£,GBP,https://www.dior.com/beauty/version-5.14327481...,https://www.dior.com/beauty/en_gb/fragrance-be...,https://www.dior.com,"Directly inspired by runway shows, the Couture...",NaN,palette,eyeshadow,[],2017-12-03T23:22:53.414Z,2017-12-26T00:33:00.563Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#C48A80', 'colour_name': '000'}]"
689,274,pacifica,Pacifica Natural Minerals Solar Complete Color...,60.00,NaN,NaN,https://d3t32hsnjxo7q6.cloudfront.net/i/baf991...,https://well.ca/products/pacifica-natural-mine...,https://well.ca,All you need to look naturally gorgeous! The ...,4.9,NaN,bronzer,"['Vegan', 'Natural']",2016-10-01T18:30:02.836Z,2017-12-23T21:08:48.370Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,[]
676,287,mistura,Mistura 6-in-1 Beauty Solution,56.49,NaN,NaN,https://d3t32hsnjxo7q6.cloudfront.net/i/d45c12...,https://well.ca/products/mistura-6-in-1-beauty...,https://well.ca,Mistura’s incredible 6-in-1 Beauty Solution po...,2.6,NaN,eyeshadow,['Canadian'],2016-10-01T18:30:21.480Z,2017-12-23T21:08:14.685Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#DBAA90', 'colour_name': 'colo..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
377,649,iman,Amplify Mascara Black Ink,NaN,NaN,NaN,http://imancosmetics.com/resources/uploads/pro...,http://imancosmetics.com/shop/products/eyes/am...,http://imancosmetics.com/,"24oz (7g) Thickens, lengthens & separates lash...",NaN,NaN,mascara,[],2016-10-03T14:05:11.236Z,2017-12-23T20:51:28.535Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,[]
378,648,iman,Perfect Eyebrow Pencil Blackest Brown,NaN,NaN,NaN,http://imancosmetics.com/resources/uploads/pro...,http://imancosmetics.com/shop/products/eyes/br...,http://imancosmetics.com/,0.05oz (1.5g) Versatile new product that combi...,NaN,NaN,eyebrow,[],2016-10-03T14:05:06.144Z,2017-12-23T20:51:28.352Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,[]
379,647,iman,Perfect Eye Pencil Ebony,NaN,NaN,NaN,http://imancosmetics.com/resources/uploads/pro...,http://imancosmetics.com/shop/products/eyes/ey...,http://imancosmetics.com/,0.05oz (1.5g) Expertly defines & lines eyes. M...,NaN,pencil,eyeliner,[],2016-10-03T14:05:00.721Z,2017-12-23T20:51:24.963Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#283434', 'colour_name': 'Blac..."
380,646,iman,Luxury Moisturizing Lipstick IMAN Nude,NaN,NaN,NaN,http://imancosmetics.com/resources/uploads/pro...,http://imancosmetics.com/shop/products/lips/li...,http://imancosmetics.com/,"13oz (3.7g) Luscious creamy, semi-matte lip co...",NaN,lipstick,lipstick,[],2016-10-03T14:04:54.792Z,2017-12-23T20:51:22.894Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#d27d56', 'colour_name': 'NEW ..."
381,645,iman,Luxury Eye Shadow Bejeweled,NaN,NaN,NaN,http://imancosmetics.com/resources/uploads/pro...,http://imancosmetics.com/shop/products/eyes/ey...,http://imancosmetics.com/,"0.05oz (1.42g) Silky, long-lasting crease-resi...",NaN,NaN,eyeshadow,[],2016-10-03T14:04:49.180Z,2017-12-23T20:51:19.960Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#ffd9ac', 'colour_name': 'Whit..."

In [32]:
df.sort_values(by=['brand'], ascending=False)

,id,brand,name,price,price_sign,currency,image_link,product_link,website_link,description,rating,category,product_type,tag_list,created_at,updated_at,product_api_url,api_featured_image,product_colors
7,1041,zorah biocosmetiques,Liquid Liner,0.00,$,USD,https://www.purpicks.com/wp-content/uploads/20...,https://www.purpicks.com/product/zorah-biocosm...,https://purpicks.com/,<strong>12 hours of long-lasting</strong> inte...,NaN,liquid,eyeliner,"['purpicks', 'EcoCert']",2018-06-30T19:19:32.312Z,2018-09-02T22:52:06.723Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#000000', 'colour_name': 'Blac..."
8,1040,zorah biocosmetiques,Eyeshadow,0.00,$,USD,https://www.purpicks.com/wp-content/uploads/20...,https://www.purpicks.com/product/zorah-eyeshadow/,https://purpicks.com/,<strong>Product Description</strong>Anti-aging...,NaN,NaN,eyeshadow,"['purpicks', 'EcoCert']",2018-06-30T19:19:32.252Z,2018-09-02T22:52:06.714Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#966A54', 'colour_name': 'Saha..."
759,191,zorah,Zorah Liquid Liner,24.00,NaN,NaN,https://d3t32hsnjxo7q6.cloudfront.net/i/3dc157...,https://well.ca/products/zorah-liquid-liner_99...,https://well.ca,Zorah Liquid Liner gives you 12 hours of long-...,3.3,liquid,eyeliner,"['Natural', 'Organic', 'Vegan', 'Gluten Free',...",2016-10-01T18:28:07.638Z,2017-12-23T20:51:18.506Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#000000', 'colour_name': 'Blac..."
881,50,zorah,Zorah Mascara Lengthing,27.00,NaN,NaN,https://d3t32hsnjxo7q6.cloudfront.net/i/dba243...,https://well.ca/products/zorah-mascara-lengthi...,https://well.ca,This lengthening mascara is made with a unique...,4.8,NaN,mascara,"['Natural', 'Organic', 'Gluten Free', 'Canadian']",2016-10-01T18:11:43.566Z,2017-12-23T20:50:54.486Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,[]
658,305,wet n wild,Wet n Wild Color Icon Eyeshadow Trio,4.79,NaN,NaN,https://d3t32hsnjxo7q6.cloudfront.net/i/07ea2b...,https://well.ca/products/wet-n-wild-color-icon...,https://well.ca,This coordinating trio of shades takes the gue...,5.0,NaN,eyeshadow,[],2016-10-01T18:30:53.725Z,2017-12-23T21:08:17.940Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
617,347,NaN,DaLish Silk to Matte Foundation,44.00,NaN,NaN,https://d3t32hsnjxo7q6.cloudfront.net/i/e98af1...,https://well.ca/products/dalish-silk-to-matte-...,https://well.ca,This long-wear DaLish foundation starts out si...,4.0,liquid,foundation,"['Canadian', 'Natural']",2016-10-01T18:32:11.060Z,2017-12-23T21:08:25.741Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#edbc92', 'colour_name': 'F01 ..."
731,227,NaN,Earth Lab Vegan Mineral Eye Pencil,18.00,NaN,NaN,https://d3t32hsnjxo7q6.cloudfront.net/i/e43ef1...,https://well.ca/products/earth-lab-vegan-miner...,https://well.ca,These natural minerals eye pencils are made fr...,3.4,pencil,eyeliner,"['Natural', 'Vegan', 'Canadian']",2016-10-01T18:28:52.926Z,2017-12-23T20:51:30.288Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#322423', 'colour_name': 'Espr..."
743,210,NaN,Pysicians Formula Eye Booster Cushion Liquid L...,15.99,NaN,NaN,https://d3t32hsnjxo7q6.cloudfront.net/i/7edeec...,https://well.ca/products/pysicians-formula-eye...,https://well.ca,Unique & Professional Cushion Eyeliner: Innova...,NaN,liquid,eyeliner,"['Gluten Free', 'Natural']",2016-10-01T18:28:31.363Z,2017-12-23T20:51:25.270Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,[]
910,21,NaN,Earth Lab Raw Mascara,24.00,NaN,NaN,https://d3t32hsnjxo7q6.cloudfront.net/i/823cec...,https://well.ca/products/earth-lab-raw-mascara...,https://well.ca,"This 100% natural, botanical based formula gli...",4.1,NaN,mascara,"['Natural', 'Canadian']",2016-10-01T18:11:10.938Z,2017-12-23T20:31:49.596Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,[]
929,2,NaN,L' Oreal Paris Voluminous Mascara,9.99,NaN,NaN,https://d3t32hsnjxo7q6.cloudfront.net/i/4d671a...,https://well.ca/products/l-oreal-paris-volumin...,https://well.ca,Voluminous - Volume Building Waterproof Mascar...,4.5,NaN,mascara,[],2016-10-01T18:10:49.185Z,2017-12-23T20:31:46.436Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#231F20', 'colour_name': 'Blac..."

In [33]:
df.sort_values(by=['brand', 'name'], ascending=[False, True])

,id,brand,name,price,price_sign,currency,image_link,product_link,website_link,description,rating,category,product_type,tag_list,created_at,updated_at,product_api_url,api_featured_image,product_colors
8,1040,zorah biocosmetiques,Eyeshadow,0.00,$,USD,https://www.purpicks.com/wp-content/uploads/20...,https://www.purpicks.com/product/zorah-eyeshadow/,https://purpicks.com/,<strong>Product Description</strong>Anti-aging...,NaN,NaN,eyeshadow,"['purpicks', 'EcoCert']",2018-06-30T19:19:32.252Z,2018-09-02T22:52:06.714Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#966A54', 'colour_name': 'Saha..."
7,1041,zorah biocosmetiques,Liquid Liner,0.00,$,USD,https://www.purpicks.com/wp-content/uploads/20...,https://www.purpicks.com/product/zorah-biocosm...,https://purpicks.com/,<strong>12 hours of long-lasting</strong> inte...,NaN,liquid,eyeliner,"['purpicks', 'EcoCert']",2018-06-30T19:19:32.312Z,2018-09-02T22:52:06.723Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#000000', 'colour_name': 'Blac..."
759,191,zorah,Zorah Liquid Liner,24.00,NaN,NaN,https://d3t32hsnjxo7q6.cloudfront.net/i/3dc157...,https://well.ca/products/zorah-liquid-liner_99...,https://well.ca,Zorah Liquid Liner gives you 12 hours of long-...,3.3,liquid,eyeliner,"['Natural', 'Organic', 'Vegan', 'Gluten Free',...",2016-10-01T18:28:07.638Z,2017-12-23T20:51:18.506Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#000000', 'colour_name': 'Blac..."
881,50,zorah,Zorah Mascara Lengthing,27.00,NaN,NaN,https://d3t32hsnjxo7q6.cloudfront.net/i/dba243...,https://well.ca/products/zorah-mascara-lengthi...,https://well.ca,This lengthening mascara is made with a unique...,4.8,NaN,mascara,"['Natural', 'Organic', 'Gluten Free', 'Canadian']",2016-10-01T18:11:43.566Z,2017-12-23T20:50:54.486Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,[]
681,282,wet n wild,Wet n Wild Color Icon Eye Shadow Collection,4.99,NaN,NaN,https://d3t32hsnjxo7q6.cloudfront.net/i/9c602a...,https://well.ca/products/wet-n-wild-color-icon...,https://well.ca,"Eight dynamic, perfectly color-coordinated sha...",4.2,palette,eyeshadow,[],2016-10-01T18:30:15.859Z,2017-12-26T00:39:05.163Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503,475,NaN,Fake Bake Blush Legal Sunburn,15.99,NaN,NaN,https://d3t32hsnjxo7q6.cloudfront.net/i/a20f36...,https://well.ca/products/fake-bake-blush-legal...,https://well.ca,Give your cheeks a sun kissed glow with Fake B...,5.0,powder,blush,[],2016-10-01T18:35:36.689Z,2017-12-23T21:08:47.614Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,[]
929,2,NaN,L' Oreal Paris Voluminous Mascara,9.99,NaN,NaN,https://d3t32hsnjxo7q6.cloudfront.net/i/4d671a...,https://well.ca/products/l-oreal-paris-volumin...,https://well.ca,Voluminous - Volume Building Waterproof Mascar...,4.5,NaN,mascara,[],2016-10-01T18:10:49.185Z,2017-12-23T20:31:46.436Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#231F20', 'colour_name': 'Blac..."
743,210,NaN,Pysicians Formula Eye Booster Cushion Liquid L...,15.99,NaN,NaN,https://d3t32hsnjxo7q6.cloudfront.net/i/7edeec...,https://well.ca/products/pysicians-formula-eye...,https://well.ca,Unique & Professional Cushion Eyeliner: Innova...,NaN,liquid,eyeliner,"['Gluten Free', 'Natural']",2016-10-01T18:28:31.363Z,2017-12-23T20:51:25.270Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,[]
509,469,NaN,Saint Cosmetics Blush,28.96,NaN,NaN,https://d3t32hsnjxo7q6.cloudfront.net/i/ed6e23...,https://well.ca/products/saint-cosmetics-blush...,https://well.ca,Create naturally flushed looking cheeks with S...,NaN,powder,blush,"['Natural', 'Vegan', 'Gluten Free', 'Canadian']",2016-10-01T18:35:28.524Z,2017-12-23T21:08:42.899Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#F591A6', 'colour_name': 'Chee..."
473,507,NaN,Saint Cosmetics Bronzer,30.96,NaN,NaN,https://d3t32hsnjxo7q6.cloudfront.net/i/4f8578...,https://well.ca/products/saint-cosmetics-bronz...,https://well.ca,Saint Cosmetics' velvety smooth bronzing formu...,NaN,NaN,bronzer,"['Natural', 'Vegan', 'Gluten Free', 'Canadian']",2016-10-01T18:36:30.602Z,2017-12-23T21:08:52.329Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#B77C59', 'colour_name': 'Glow..."

In [34]:
df['brand'].unique()

array(['colourpop', 'boosh', 'deciem', 'zorah biocosmetiques',
       'w3llpeople', "sally b's skin yummies", 'rejuva minerals',
       'penny lane organics', 'nudus', 'marienatie',
       "maia's mineral galaxy", 'lotus cosmetics usa', 'green people',
       'coastal classic creation', "c'est moi", 'alva', 'glossier', 'nyx',
       'fenty', 'clinique', 'dior', 'iman', 'benefit', 'smashbox',
       'marcelle', 'stila', 'mineral fusion', nan, 'annabelle',
       'dr. hauschka', 'physicians formula', 'cargo cosmetics',
       'covergirl', 'e.l.f.', 'maybelline', 'almay', 'milani',
       'pure anada', "l'oreal", 'sante', 'revlon', 'anna sui',
       'wet n wild', 'pacifica', 'mistura', 'zorah', 'suncoat', 'moov',
       'misa', 'salon perfect', 'orly', 'china glaze', 'essie',
       'butter london', 'sinful colours', 'piggy paint', 'dalish',
       "burt's bees"], dtype=object)

In [35]:
df['price'].value_counts()

price
10.99    42
0.00     40
9.99     33
10.00    29
7.00     28
         ..
38.50     1
46.99     1
52.00     1
55.00     1
23.49     1
Name: count, Length: 157, dtype: int64

In [36]:
df['price'].value_counts(normalize=True)

price
10.99    0.045802
0.00     0.043621
9.99     0.035987
10.00    0.031625
7.00     0.030534
           ...
38.50    0.001091
46.99    0.001091
52.00    0.001091
55.00    0.001091
23.49    0.001091
Name: proportion, Length: 157, dtype: float64

In [37]:
df.shape

(931, 19)

In [38]:
df['price'].size

931

In [39]:
df['price'].value_counts() / df['price'].size

price
10.99    0.045113
0.00     0.042965
9.99     0.035446
10.00    0.031149
7.00     0.030075
           ...
38.50    0.001074
46.99    0.001074
52.00    0.001074
55.00    0.001074
23.49    0.001074
Name: count, Length: 157, dtype: float64

In [40]:
42 / 931

0.045112781954887216

Criando Coluna

In [41]:
media_preco = df['price'].mean()
media_preco

16.508593238822247

In [42]:
df['preco_acima_media'] = df['price'] > media_preco

In [43]:
df[['id', 'brand', 'name', 'price', 'preco_acima_media']].tail()

,id,brand,name,price,preco_acima_media
926,5,pacifica,Pacifica Stellar Gaze Length & Strength Minera...,28.00,True
927,4,physicians formula,Physicians Formula Organic Wear FakeOut Mascara,15.79,False
928,3,physicians formula,Physicians Formula Organic Wear Lash Boosting ...,15.79,False
929,2,NaN,L' Oreal Paris Voluminous Mascara,9.99,False
930,1,pure anada,Pure Anada Natural Mascara,14.00,False

Apagando coluna

In [44]:
df.drop(columns=['image_link', 'product_link', 'website_link'])

,id,brand,name,price,price_sign,currency,description,rating,category,product_type,tag_list,created_at,updated_at,product_api_url,api_featured_image,product_colors,preco_acima_media
0,1048,colourpop,Lippie Pencil,5.00,$,CAD,Lippie Pencil A long-wearing and high-intensit...,NaN,pencil,lip_liner,"['cruelty free', 'Vegan']",2018-07-08T23:45:08.056Z,2018-07-09T00:53:23.301Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#B28378', 'colour_name': 'BFF ...",False
1,1047,colourpop,Blotted Lip,5.50,$,CAD,Blotted Lip Sheer matte lipstick that creates ...,NaN,lipstick,lipstick,"['cruelty free', 'Vegan']",2018-07-08T22:01:20.178Z,2018-07-09T00:53:23.287Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#b72227', 'colour_name': ""Bee'...",False
2,1046,colourpop,Lippie Stix,5.50,$,CAD,"Lippie Stix Formula contains Vitamin E, Mango,...",NaN,lipstick,lipstick,"['cruelty free', 'Vegan']",2018-07-08T21:47:49.858Z,2018-07-09T00:53:23.274Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#F2DEC3', 'colour_name': 'Fair...",False
3,1045,colourpop,No Filter Foundation,12.00,$,CAD,"Developed for the Selfie Age, our buildable fu...",NaN,liquid,foundation,"['cruelty free', 'Vegan']",2018-07-08T18:22:25.273Z,2018-07-09T00:53:23.313Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#F2DEC3', 'colour_name': 'Fair...",False
4,1044,boosh,Lipstick,26.00,$,CAD,All of our products are free from lead and hea...,NaN,lipstick,lipstick,"['Chemical Free', 'Organic']",2018-07-08T17:32:28.088Z,2018-09-02T22:52:06.669Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#CB4975', 'colour_name': 'Babs...",True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
926,5,pacifica,Pacifica Stellar Gaze Length & Strength Minera...,28.00,NaN,NaN,You will fall in love with Pacifica's long las...,4.2,NaN,mascara,"['Natural', 'Vegan']",2016-10-01T18:10:52.756Z,2017-12-23T20:31:47.230Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,[],True
927,4,physicians formula,Physicians Formula Organic Wear FakeOut Mascara,15.79,NaN,NaN,Physicians Formula Organic Wear FakeOut Mascar...,3.9,NaN,mascara,"['Natural', 'Gluten Free']",2016-10-01T18:10:51.387Z,2017-12-23T20:31:47.075Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#000000', 'colour_name': 'Ultr...",False
928,3,physicians formula,Physicians Formula Organic Wear Lash Boosting ...,15.79,NaN,NaN,Physicians Formula Organic Wear Lash Boosting ...,3.7,NaN,mascara,"['Natural', 'Gluten Free']",2016-10-01T18:10:50.417Z,2017-12-23T20:31:46.951Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#000000', 'colour_name': 'Ultr...",False
929,2,NaN,L' Oreal Paris Voluminous Mascara,9.99,NaN,NaN,Voluminous - Volume Building Waterproof Mascar...,4.5,NaN,mascara,[],2016-10-01T18:10:49.185Z,2017-12-23T20:31:46.436Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#231F20', 'colour_name': 'Blac...",False
930,1,pure anada,Pure Anada Natural Mascara,14.00,NaN,NaN,"Finally, a natural mascara you can feel good a...",4.6,NaN,mascara,"['Natural', 'Gluten Free', 'Canadian']",2016-10-01T18:10:46.893Z,2017-12-23T20:31:46.013Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#000000', 'colour_name': 'Blac...",False

In [45]:
df.head()

,id,brand,name,price,price_sign,currency,image_link,product_link,website_link,description,rating,category,product_type,tag_list,created_at,updated_at,product_api_url,api_featured_image,product_colors,preco_acima_media
0,1048,colourpop,Lippie Pencil,5.0,$,CAD,https://cdn.shopify.com/s/files/1/1338/0845/co...,https://colourpop.com/collections/lippie-pencil,https://colourpop.com,Lippie Pencil A long-wearing and high-intensit...,NaN,pencil,lip_liner,"['cruelty free', 'Vegan']",2018-07-08T23:45:08.056Z,2018-07-09T00:53:23.301Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#B28378', 'colour_name': 'BFF ...",False
1,1047,colourpop,Blotted Lip,5.5,$,CAD,https://cdn.shopify.com/s/files/1/1338/0845/pr...,https://colourpop.com/collections/lippie-stix?...,https://colourpop.com,Blotted Lip Sheer matte lipstick that creates ...,NaN,lipstick,lipstick,"['cruelty free', 'Vegan']",2018-07-08T22:01:20.178Z,2018-07-09T00:53:23.287Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#b72227', 'colour_name': ""Bee'...",False
2,1046,colourpop,Lippie Stix,5.5,$,CAD,https://cdn.shopify.com/s/files/1/1338/0845/co...,https://colourpop.com/collections/lippie-stix,https://colourpop.com,"Lippie Stix Formula contains Vitamin E, Mango,...",NaN,lipstick,lipstick,"['cruelty free', 'Vegan']",2018-07-08T21:47:49.858Z,2018-07-09T00:53:23.274Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#F2DEC3', 'colour_name': 'Fair...",False
3,1045,colourpop,No Filter Foundation,12.0,$,CAD,https://cdn.shopify.com/s/files/1/1338/0845/pr...,https://colourpop.com/products/no-filter-matte...,https://colourpop.com/products/no-filter-matte...,"Developed for the Selfie Age, our buildable fu...",NaN,liquid,foundation,"['cruelty free', 'Vegan']",2018-07-08T18:22:25.273Z,2018-07-09T00:53:23.313Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#F2DEC3', 'colour_name': 'Fair...",False
4,1044,boosh,Lipstick,26.0,$,CAD,https://cdn.shopify.com/s/files/1/1016/3243/pr...,https://www.boosh.ca/collections/all,https://www.boosh.ca/,All of our products are free from lead and hea...,NaN,lipstick,lipstick,"['Chemical Free', 'Organic']",2018-07-08T17:32:28.088Z,2018-09-02T22:52:06.669Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#CB4975', 'colour_name': 'Babs...",True

In [46]:
# df.drop(columns=['image_link', 'product_link', 'website_link'], inplace=True) # Ou
df = df.drop(columns=['image_link', 'product_link', 'website_link'])

df.head()

,id,brand,name,price,price_sign,currency,description,rating,category,product_type,tag_list,created_at,updated_at,product_api_url,api_featured_image,product_colors,preco_acima_media
0,1048,colourpop,Lippie Pencil,5.0,$,CAD,Lippie Pencil A long-wearing and high-intensit...,NaN,pencil,lip_liner,"['cruelty free', 'Vegan']",2018-07-08T23:45:08.056Z,2018-07-09T00:53:23.301Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#B28378', 'colour_name': 'BFF ...",False
1,1047,colourpop,Blotted Lip,5.5,$,CAD,Blotted Lip Sheer matte lipstick that creates ...,NaN,lipstick,lipstick,"['cruelty free', 'Vegan']",2018-07-08T22:01:20.178Z,2018-07-09T00:53:23.287Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#b72227', 'colour_name': ""Bee'...",False
2,1046,colourpop,Lippie Stix,5.5,$,CAD,"Lippie Stix Formula contains Vitamin E, Mango,...",NaN,lipstick,lipstick,"['cruelty free', 'Vegan']",2018-07-08T21:47:49.858Z,2018-07-09T00:53:23.274Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#F2DEC3', 'colour_name': 'Fair...",False
3,1045,colourpop,No Filter Foundation,12.0,$,CAD,"Developed for the Selfie Age, our buildable fu...",NaN,liquid,foundation,"['cruelty free', 'Vegan']",2018-07-08T18:22:25.273Z,2018-07-09T00:53:23.313Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#F2DEC3', 'colour_name': 'Fair...",False
4,1044,boosh,Lipstick,26.0,$,CAD,All of our products are free from lead and hea...,NaN,lipstick,lipstick,"['Chemical Free', 'Organic']",2018-07-08T17:32:28.088Z,2018-09-02T22:52:06.669Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#CB4975', 'colour_name': 'Babs...",True

In [47]:
produtos_preco_entre_muito_baratos = df['price'].between(1, 5)

df[produtos_preco_entre_muito_baratos].head()

,id,brand,name,price,price_sign,currency,description,rating,category,product_type,tag_list,created_at,updated_at,product_api_url,api_featured_image,product_colors,preco_acima_media
0,1048,colourpop,Lippie Pencil,5.00,$,CAD,Lippie Pencil A long-wearing and high-intensit...,NaN,pencil,lip_liner,"['cruelty free', 'Vegan']",2018-07-08T23:45:08.056Z,2018-07-09T00:53:23.301Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#B28378', 'colour_name': 'BFF ...",False
75,973,nyx,Auto Eyebrow Pencil,4.75,$,USD,Create flawless arches with this eyebrow penci...,NaN,NaN,eyebrow,[],2017-12-24T02:32:34.961Z,2017-12-24T02:32:35.432Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#B8957F', 'colour_name': 'Ligh...",False
89,959,nyx,Slim Eye Pencil,4.00,$,USD,"Slim, trim, but never prim. Our Slim Eye Penci...",NaN,pencil,eyeliner,[],2017-12-24T02:32:09.470Z,2017-12-24T02:32:10.343Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#9BC98B', 'colour_name': 'Gree...",False
90,958,nyx,Retractable Eye Liner,5.00,$,USD,Twist and shout! Renowned for its extreme last...,NaN,pencil,eyeliner,[],2017-12-24T02:32:05.574Z,2017-12-24T02:32:06.056Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#776F26', 'colour_name': 'Gold...",False
92,956,nyx,Jumbo Eye Pencil,4.50,$,USD,NaN,NaN,pencil,eyeliner,[],2017-12-24T02:31:53.675Z,2017-12-24T02:31:54.390Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#FFACC1', 'colour_name': 'Stra...",False

##### Projeto ideias
- Percorrer o diretório pegando todas as figuras, processando augmentos e salvando as figuras
- Percorrer o diretório pegando todos os áudios mp3, tirando os metadados: criando no final um csv ['nome_arquivo', 'taxa...']
- Percorrer um arquivo de log, separar em um csv ['data', 'tipo (ex. Error, Warning, Info, etc)', 'texto do log']
    - Análise dias da semana que temos mais erros, período do dia que temos mais erros, etc 
- Escolher um dataset para:
    -  tratar os dados, dados faltantes
    -  separar em csv/tabelas ex. produtos_baratos.csv e produtos_caros.csv

##### Criar um indice de técnicas/dicas/etc
##### Indicar na célula a técnicas/dicas/etc utilizada
##### Colocar no github

In [49]:
cotacao_dolar = 4.98

In [52]:
df['preco_reais'] = df['price'] * cotacao_dolar
df[['id', 'brand', 'name', 'price', 'preco_reais']].head()

     id      brand                  name  price  preco_reais
0  1048  colourpop         Lippie Pencil    5.0        24.90
1  1047  colourpop           Blotted Lip    5.5        27.39
2  1046  colourpop           Lippie Stix    5.5        27.39
3  1045  colourpop  No Filter Foundation   12.0        59.76
4  1044      boosh              Lipstick   26.0       129.48

In [53]:
df = df.rename(
    columns={
        'price':  'price_dollar',
        'preco_reais': 'preco_br'
    })
df[['id', 'brand', 'name', 'price_dollar', 'preco_br']].head()

     id      brand                  name  price_dollar  preco_br
0  1048  colourpop         Lippie Pencil           5.0     24.90
1  1047  colourpop           Blotted Lip           5.5     27.39
2  1046  colourpop           Lippie Stix           5.5     27.39
3  1045  colourpop  No Filter Foundation          12.0     59.76
4  1044      boosh              Lipstick          26.0    129.48

## NaN
Tem como base o https://en.wikipedia.org/wiki/IEEE_754  
Resumindo: NaN é um valor de ponto flutuante especial que não pode ser convertido em nenhum outro tipo de dado além do próprio float

In [58]:
import numpy as np

In [60]:
notas_provas = pd.DataFrame({
    'nome': ['A', 'B', 'C', 'D', 'E'],
    'nota': [85, np.nan, 95, 78, np.nan]
})
notas_provas

  nome  nota
0    A  85.0
1    B   NaN
2    C  95.0
3    D  78.0
4    E   NaN

In [61]:
notas_provas['nota'].mean()

86.0

In [62]:
(85 + 95 + 78) / 3

86.0

In [67]:
notas_provas.shape[0]

5

In [68]:
notas_provas['nota'].sum() / notas_provas.shape[0]

51.6

In [70]:
df['rating'].isna()

0       True
1       True
2       True
3       True
4       True
       ...
926    False
927    False
928    False
929    False
930    False
Name: rating, Length: 931, dtype: bool

In [71]:
df[df['rating'].isna()]

,id,brand,name,price_dollar,price_sign,currency,description,rating,category,product_type,tag_list,created_at,updated_at,product_api_url,api_featured_image,product_colors,preco_acima_media,preco_br
0,1048,colourpop,Lippie Pencil,5.00,$,CAD,Lippie Pencil A long-wearing and high-intensit...,NaN,pencil,lip_liner,"['cruelty free', 'Vegan']",2018-07-08T23:45:08.056Z,2018-07-09T00:53:23.301Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#B28378', 'colour_name': 'BFF ...",False,24.9000
1,1047,colourpop,Blotted Lip,5.50,$,CAD,Blotted Lip Sheer matte lipstick that creates ...,NaN,lipstick,lipstick,"['cruelty free', 'Vegan']",2018-07-08T22:01:20.178Z,2018-07-09T00:53:23.287Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#b72227', 'colour_name': ""Bee'...",False,27.3900
2,1046,colourpop,Lippie Stix,5.50,$,CAD,"Lippie Stix Formula contains Vitamin E, Mango,...",NaN,lipstick,lipstick,"['cruelty free', 'Vegan']",2018-07-08T21:47:49.858Z,2018-07-09T00:53:23.274Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#F2DEC3', 'colour_name': 'Fair...",False,27.3900
3,1045,colourpop,No Filter Foundation,12.00,$,CAD,"Developed for the Selfie Age, our buildable fu...",NaN,liquid,foundation,"['cruelty free', 'Vegan']",2018-07-08T18:22:25.273Z,2018-07-09T00:53:23.313Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#F2DEC3', 'colour_name': 'Fair...",False,59.7600
4,1044,boosh,Lipstick,26.00,$,CAD,All of our products are free from lead and hea...,NaN,lipstick,lipstick,"['Chemical Free', 'Organic']",2018-07-08T17:32:28.088Z,2018-09-02T22:52:06.669Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#CB4975', 'colour_name': 'Babs...",True,129.4800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
878,53,covergirl,CoverGirl Professional Mascara Curved Brush Ve...,6.99,NaN,NaN,"Volumize, lengthen and define like a pro! Cove...",NaN,NaN,mascara,[],2016-10-01T18:11:48.408Z,2017-12-23T20:31:53.214Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,[],False,34.8102
879,52,covergirl,CoverGirl Professional Mascara Curved Brush Bl...,6.99,NaN,NaN,"Volumize, lengthen and define like a pro! Cove...",NaN,NaN,mascara,[],2016-10-01T18:11:46.356Z,2017-12-23T20:31:52.960Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,[],False,34.8102
890,41,l'oreal,L'Oreal Paris Voluminous Butterfly Mascara,13.49,NaN,NaN,Stretch and extend your lashes like wings! In...,NaN,NaN,mascara,[],2016-10-01T18:11:33.681Z,2017-12-23T20:50:53.374Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#000000', 'colour_name': 'Blac...",False,67.1802
891,40,covergirl,CoverGirl Professional Waterproof Mascara Very...,6.99,NaN,NaN,"Volumize, lengthen and define like a pro! Cove...",NaN,NaN,mascara,[],2016-10-01T18:11:32.686Z,2017-12-23T20:50:53.262Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,[],False,34.8102
920,11,maybelline,Maybelline Volum' Express The Rocket Mascara,10.99,NaN,NaN,"Explosive Volume in Rocket Time! 8X Bigger, Sm...",NaN,NaN,mascara,[],2016-10-01T18:10:58.856Z,2017-12-23T20:31:47.966Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#000000', 'colour_name': 'Blac...",False,54.7302

In [72]:
True + True

2

In [81]:
df = pd.read_csv('produtos.csv')

df['rating'].isna().sum()

591

In [82]:
df.isna().sum()

id                      0
brand                  12
name                    0
price                  14
price_sign            563
currency              563
image_link              0
product_link            0
website_link            0
description            25
rating                591
category              424
product_type            0
tag_list                0
created_at              0
updated_at              0
product_api_url         0
api_featured_image      0
product_colors          0
dtype: int64

In [83]:
df.shape

(931, 19)

In [79]:
notas_provas.dropna()

  nome  nota
0    A  85.0
2    C  95.0
3    D  78.0

## Concat
É uma funcão para **juntar** dataframes

In [86]:
df1 = pd.DataFrame({
    'a': [1, 2, 3],
    'b': [4, 5, 6],
    'c': [7, 8 ,9]
})


df2 = pd.DataFrame({
    'b': [1, 2, 3],
    'c': [4, 5, 6],
    'd': [7, 8 ,9]
})

display(df1)
display(df2)

   a  b  c
0  1  4  7
1  2  5  8
2  3  6  9

   b  c  d
0  1  4  7
1  2  5  8
2  3  6  9

In [89]:
df3 = pd.concat([df1, df2])
df3

     a  b  c    d
0  1.0  4  7  NaN
1  2.0  5  8  NaN
2  3.0  6  9  NaN
0  NaN  1  4  7.0
1  NaN  2  5  8.0
2  NaN  3  6  9.0

In [90]:
df3.loc[0]

     a  b  c    d
0  1.0  4  7  NaN
0  NaN  1  4  7.0

In [91]:
df3 = pd.concat([df1, df2], axis=1)
df3

   a  b  c  b  c  d
0  1  4  7  1  4  7
1  2  5  8  2  5  8
2  3  6  9  3  6  9

In [92]:
display(df1.loc[0])
display(df2.loc[0])

a    1
b    4
c    7
Name: 0, dtype: int64

b    1
c    4
d    7
Name: 0, dtype: int64

## Merge
Permite o **cruzamento** de bases de dados
  
<img src="https://community.qlik.com/legacyfs/online/87693_all-joins.png" width=450>

In [99]:
df4 = pd.DataFrame({
    'pais': ['br', 'pt', 'it'],
    'valor1': [1, 2, 3],
    'valor2': [3, 4, 5]
})

df5 = pd.DataFrame({
    'pais': ['br', 'pt', 'ar'],
    'valor1': [1, 2, 3],
    'valor2': [3, 4, 5]
})
display(df4)
display(df5)

  pais  valor1  valor2
0   br       1       3
1   pt       2       4
2   it       3       5

  pais  valor1  valor2
0   br       1       3
1   pt       2       4
2   ar       3       5

In [100]:
df4.merge(df5, how='inner', on='pais')

  pais  valor1_x  valor2_x  valor1_y  valor2_y
0   br         1         3         1         3
1   pt         2         4         2         4

In [101]:
df4.merge(df5, how='left', on='pais')

  pais  valor1_x  valor2_x  valor1_y  valor2_y
0   br         1         3       1.0       3.0
1   pt         2         4       2.0       4.0
2   it         3         5       NaN       NaN

In [102]:
df4.merge(df5, how='outer', on='pais')

  pais  valor1_x  valor2_x  valor1_y  valor2_y
0   ar       NaN       NaN       3.0       5.0
1   br       1.0       3.0       1.0       3.0
2   it       3.0       5.0       NaN       NaN
3   pt       2.0       4.0       2.0       4.0

Com colunas diferentes

In [103]:
df4 = pd.DataFrame({
    'country': ['br', 'pt', 'it'],
    'valor1': [1, 2, 3],
    'valor2': [3, 4, 5]
})

df5 = pd.DataFrame({
    'pais': ['br', 'pt', 'ar'],
    'valor1': [1, 2, 3],
    'valor2': [3, 4, 5]
})
display(df4)
display(df5)

  country  valor1  valor2
0      br       1       3
1      pt       2       4
2      it       3       5

  pais  valor1  valor2
0   br       1       3
1   pt       2       4
2   ar       3       5

In [105]:
df4.merge(df5, how='inner', left_on='country', right_on='pais')

  country  valor1_x  valor2_x pais  valor1_y  valor2_y
0      br         1         3   br         1         3
1      pt         2         4   pt         2         4

## Join
A juncão é baseada nos índices (definidos por set_index)

In [106]:
df4 = pd.DataFrame({
    'pais': ['br', 'pt', 'it'],
    'valor1': [1, 2, 3],
    'valor2': [3, 4, 5]
})

df5 = pd.DataFrame({
    'pais': ['br', 'pt', 'ar'],
    'valor1': [1, 2, 3],
    'valor2': [3, 4, 5]
})
display(df4)
display(df5)

  pais  valor1  valor2
0   br       1       3
1   pt       2       4
2   it       3       5

  pais  valor1  valor2
0   br       1       3
1   pt       2       4
2   ar       3       5

In [108]:
df4.join(df5, lsuffix='_esq', rsuffix='_dir')

  pais_esq  valor1_esq  valor2_esq pais_dir  valor1_dir  valor2_dir
0       br           1           3       br           1           3
1       pt           2           4       pt           2           4
2       it           3           5       ar           3           5

### Group By

In [109]:
df.head()

,id,brand,name,price,price_sign,currency,image_link,product_link,website_link,description,rating,category,product_type,tag_list,created_at,updated_at,product_api_url,api_featured_image,product_colors
0,1048,colourpop,Lippie Pencil,5.0,$,CAD,https://cdn.shopify.com/s/files/1/1338/0845/co...,https://colourpop.com/collections/lippie-pencil,https://colourpop.com,Lippie Pencil A long-wearing and high-intensit...,NaN,pencil,lip_liner,"['cruelty free', 'Vegan']",2018-07-08T23:45:08.056Z,2018-07-09T00:53:23.301Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#B28378', 'colour_name': 'BFF ..."
1,1047,colourpop,Blotted Lip,5.5,$,CAD,https://cdn.shopify.com/s/files/1/1338/0845/pr...,https://colourpop.com/collections/lippie-stix?...,https://colourpop.com,Blotted Lip Sheer matte lipstick that creates ...,NaN,lipstick,lipstick,"['cruelty free', 'Vegan']",2018-07-08T22:01:20.178Z,2018-07-09T00:53:23.287Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#b72227', 'colour_name': ""Bee'..."
2,1046,colourpop,Lippie Stix,5.5,$,CAD,https://cdn.shopify.com/s/files/1/1338/0845/co...,https://colourpop.com/collections/lippie-stix,https://colourpop.com,"Lippie Stix Formula contains Vitamin E, Mango,...",NaN,lipstick,lipstick,"['cruelty free', 'Vegan']",2018-07-08T21:47:49.858Z,2018-07-09T00:53:23.274Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#F2DEC3', 'colour_name': 'Fair..."
3,1045,colourpop,No Filter Foundation,12.0,$,CAD,https://cdn.shopify.com/s/files/1/1338/0845/pr...,https://colourpop.com/products/no-filter-matte...,https://colourpop.com/products/no-filter-matte...,"Developed for the Selfie Age, our buildable fu...",NaN,liquid,foundation,"['cruelty free', 'Vegan']",2018-07-08T18:22:25.273Z,2018-07-09T00:53:23.313Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#F2DEC3', 'colour_name': 'Fair..."
4,1044,boosh,Lipstick,26.0,$,CAD,https://cdn.shopify.com/s/files/1/1016/3243/pr...,https://www.boosh.ca/collections/all,https://www.boosh.ca/,All of our products are free from lead and hea...,NaN,lipstick,lipstick,"['Chemical Free', 'Organic']",2018-07-08T17:32:28.088Z,2018-09-02T22:52:06.669Z,http://makeup-api.herokuapp.com/api/v1/product...,//s3.amazonaws.com/donovanbailey/products/api_...,"[{'hex_value': '#CB4975', 'colour_name': 'Babs..."

In [113]:
df[['brand', 'price']].groupby(['brand']).sum()

                            price
brand
almay                      177.26
alva                         9.95
anna sui                   132.00
annabelle                  107.86
benefit                   1252.00
boosh                       26.00
burt's bees                 19.98
butter london               50.96
c'est moi                    0.00
cargo cosmetics            585.00
china glaze                  8.00
clinique                  2094.35
coastal classic creation     0.00
colourpop                   28.00
covergirl                  522.96
dalish                      22.00
deciem                      13.60
dior                      2024.50
dr. hauschka               407.00
e.l.f.                     182.73
essie                       40.00
fenty                      116.00
glossier                   150.00
green people                 0.00
iman                         0.00
l'oreal                    638.11
lotus cosmetics usa          0.00
maia's mineral galaxy        0.00
marcelle                   218.85
marienatie                   0.00
maybelline                 601.46
milani                     117.87
mineral fusion             203.00
misa                         9.39
mistura                     56.49
moov                        44.97
nudus                        0.00
nyx                       1380.58
orly                        42.98
pacifica                   330.96
penny lane organics          0.00
physicians formula         740.17
piggy paint                 11.99
pure anada                 227.99
rejuva minerals              0.00
revlon                     391.31
sally b's skin yummies       0.00
salon perfect                6.99
sante                      132.54
sinful colours               2.99
smashbox                  1373.00
stila                      184.99
suncoat                     96.04
w3llpeople                   0.00
wet n wild                  51.68
zorah                       51.00
zorah biocosmetiques         0.00

In [119]:
df[df['brand'] == 'almay']['price'].mean()

12.661428571428575

In [122]:
(
df[['brand', 'price', 'rating']]
    .groupby(['brand'])
    .agg({
        'price': ['mean', 'min', 'max'],
        'rating': ['mean', 'count']
    })
)

                              price                  rating
                               mean    min    max      mean count
brand
almay                     12.661429   8.99  17.29  4.241667    12
alva                       9.950000   9.95   9.95       NaN     0
anna sui                  22.000000  10.00  28.00       NaN     0
annabelle                  9.805455   6.99  11.99  4.966667     6
benefit                   30.536585  16.00  75.00       NaN     0
boosh                     26.000000  26.00  26.00       NaN     0
burt's bees                9.990000   9.99   9.99  4.100000     2
butter london             25.480000  22.00  28.96  5.000000     1
c'est moi                  0.000000   0.00   0.00       NaN     0
cargo cosmetics           29.250000  19.00  42.00  4.845455    11
china glaze                8.000000   8.00   8.00  4.700000     1
clinique                  22.764674   8.50  39.00       NaN     0
coastal classic creation   0.000000   0.00   0.00       NaN     0
colourpop                  7.000000   5.00  12.00       NaN     0
covergirl                  9.684444   4.49  15.99  4.427273    33
dalish                    22.000000  22.00  22.00  3.800000     1
deciem                     6.800000   6.70   6.90       NaN     0
dior                      27.358108   0.00  77.00       NaN     0
dr. hauschka              33.916667  22.00  45.00  4.670000    10
e.l.f.                     6.767778   3.99  13.99  4.381818    22
essie                     10.000000  10.00  10.00  3.550000     4
fenty                     23.200000  18.00  34.00       NaN     0
glossier                  25.000000  20.00  32.00       NaN     0
green people               0.000000   0.00   0.00       NaN     0
iman                            NaN    NaN    NaN       NaN     0
l'oreal                   13.871957   7.79  29.99  4.323333    30
lotus cosmetics usa        0.000000   0.00   0.00       NaN     0
maia's mineral galaxy      0.000000   0.00   0.00       NaN     0
marcelle                  14.590000  10.99  22.99  4.250000     6
marienatie                 0.000000   0.00   0.00       NaN     0
maybelline                11.138148   4.49  18.49  4.082609    46
milani                     9.066923   3.99  12.99  4.480000    10
mineral fusion            25.375000  10.00  37.00  4.180000     5
misa                       9.390000   9.39   9.39  5.000000     1
mistura                   56.490000  56.49  56.49  2.600000     1
moov                      14.990000  14.99  14.99  2.500000     2
nudus                      0.000000   0.00   0.00       NaN     0
nyx                        8.418171   0.00  20.00  4.318182    11
orly                      10.745000   8.00  13.49  3.666667     3
pacifica                  25.458462  14.00  60.00  4.466667    12
penny lane organics        0.000000   0.00   0.00       NaN     0
physicians formula        17.213256   8.99  29.99  4.307692    39
piggy paint               11.990000  11.99  11.99  4.300000     1
pure anada                14.249375   8.00  25.99  4.460000    15
rejuva minerals            0.000000   0.00   0.00       NaN     0
revlon                    13.493448   6.99  19.99  4.456522    23
sally b's skin yummies     0.000000   0.00   0.00       NaN     0
salon perfect              6.990000   6.99   6.99       NaN     0
sante                     22.090000  17.29  27.49  4.083333     6
sinful colours             2.990000   2.99   2.99  4.300000     1
smashbox                  29.847826  18.00  55.00       NaN     0
stila                     46.247500  36.00  51.00       NaN     0
suncoat                   16.006667   8.29  22.49  3.766667     6
w3llpeople                 0.000000   0.00   0.00       NaN     0
wet n wild                 4.306667   1.99   6.99  4.666667     9
zorah                     25.500000  24.00  27.00  4.050000     2
zorah biocosmetiques       0.000000   0.00   0.00       NaN     0

#### Trabalhar com datas

In [124]:
dados = {
    'data': ['2024-01-01', '2024-01-01', '2024-01-02', '2024-01-02'],
    'produto': ['A', 'B', 'A', 'B'],
    'qtde': [20, 35, 25, 40]
}

df_temp = pd.DataFrame(dados)
df_temp

         data produto  qtde
0  2024-01-01       A    20
1  2024-01-01       B    35
2  2024-01-02       A    25
3  2024-01-02       B    40

In [126]:
df_temp.dtypes

data       object
produto    object
qtde        int64
dtype: object

In [ ]:
# https://docs.python.org/pt-br/3.10/library/datetime.html#strftime-and-strptime-format-codes

In [130]:
df_temp['data_tipada'] = pd.to_datetime(df_temp['data'], format='%Y-%m-%d')
df_temp.head()

         data produto  qtde data_tipada
0  2024-01-01       A    20  2024-01-01
1  2024-01-01       B    35  2024-01-01
2  2024-01-02       A    25  2024-01-02
3  2024-01-02       B    40  2024-01-02

In [131]:
df_temp.dtypes

data                   object
produto                object
qtde                    int64
data_tipada    datetime64[ns]
dtype: object

In [134]:
df_temp['mes'] = df_temp['data_tipada'].dt.month
df_temp

         data produto  qtde data_tipada  mes
0  2024-01-01       A    20  2024-01-01    1
1  2024-01-01       B    35  2024-01-01    1
2  2024-01-02       A    25  2024-01-02    1
3  2024-01-02       B    40  2024-01-02    1

In [135]:
df_temp['dia'] = df_temp['data_tipada'].dt.day
df_temp

         data produto  qtde data_tipada  mes  dia
0  2024-01-01       A    20  2024-01-01    1    1
1  2024-01-01       B    35  2024-01-01    1    1
2  2024-01-02       A    25  2024-01-02    1    2
3  2024-01-02       B    40  2024-01-02    1    2

In [137]:
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DatetimeIndex.dayofweek.html

In [136]:
df_temp['dia_semana'] = df_temp['data_tipada'].dt.dayofweek
df_temp

         data produto  qtde data_tipada  mes  dia  dia_semana
0  2024-01-01       A    20  2024-01-01    1    1           0
1  2024-01-01       B    35  2024-01-01    1    1           0
2  2024-01-02       A    25  2024-01-02    1    2           1
3  2024-01-02       B    40  2024-01-02    1    2           1

#### Dados Faltantes

In [139]:
notas_provas = pd.DataFrame({
    'nome': ['A', 'B', 'C', 'D', 'E'],
    'nota': [85, np.nan, 95, 78, np.nan]
})
notas_provas

  nome  nota
0    A  85.0
1    B   NaN
2    C  95.0
3    D  78.0
4    E   NaN

In [140]:
notas_provas.fillna(0)

  nome  nota
0    A  85.0
1    B   0.0
2    C  95.0
3    D  78.0
4    E   0.0

In [142]:
media_notas = notas_provas['nota'].mean()
novas_notas = notas_provas.fillna(media_notas)
novas_notas

  nome  nota
0    A  85.0
1    B  86.0
2    C  95.0
3    D  78.0
4    E  86.0

In [145]:
novas_notas['nota'].mean()

86.0